FROM python:3.9-slim

WORKDIR /app

RUN pip install --no-cache-dir streamlit requests pandas plotly

COPY streamlit_app.py .

ENTRYPOINT ["streamlit", "run", "streamlit_app.py", "--server.port=8501", "--server.address=0.0.0.0"] 