OPENAI_API_KEY = "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"
GROQ_API_KEY = "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"

API_URL = "http://localhost:8000/api/v1/ask"


LLM_MODEL = "llama3-70b-8192"



EMBEDDING_MODEL = "text-embedding-3-small"

VECTOR_STORE_PATH = "app/data/embeddings/faiss_index"

VECTOR_STORE_TYPE = "faiss"

CONSTITUTION_SOURCE_PATH = "app/data/constitution/source"


CHUNK_SIZE = "1000"
CHUNK_OVERLAP = "200"

NUM_RETRIEVED_DOCUMENTS = "5"